services:

        postgres-server:
                image: postgres:latest
                restart: always
                environment:
                        POSTGRES_PASSWORD: password
                ports:
                        - 5432:5432
