services:
        mysql-server:
                image: mysql:latest
                command: --default-authentication-plugin=mysql_native_password
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: password
                ports:
                        - 3306:3306

